### ISSUE TITLE
[Bug]: [@vue/compiler-sfc] Failed to resolve extends base type. While adding button component

### ISSUE THREAD

**Issue by hubcio2115** [radix-vue/shadcn-vue#207]
### Environment

```bash
Developement/Production OS: MacOS 14.1.2
Node version: 20.9.0
Package manager: bun@1.0.15
Radix Vue version: latest
Shadcn Vue version: 0.1.0
Vue version: 3.3.10
Nuxt version: 3.8.2
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.5
Client OS: MacOS 14.1.2
Browser: Firefox 120.0.1
```

### Link to minimal reproduction

https://github.com/hubcio2115/nuxt-chadcn

### Steps to reproduce

- add `components/ui` folder in `src` - because you cannot commit empty folders with git
- run `bun i`
- run `bunx schadcn-vue-@latest add button` 

### Describe the bug

I started a brand new project with `nuxti`, as per shadcn-vue instructions for js setup in the installation docs. Went through entire process and when I try to add `button` with the cli I get:
```bash
$ bunx shadcn-vue@latest add button
⠋ Installing components...[@vue/compiler-sfc] Failed to resolve extends base type.
If this previously worked in 3.2, you can instruct the compiler to ignore this extend by adding /* @v
ue-ignore */ before it, for example:

interface Props extends /* @vue-ignore */ Base {}

Note: both in 3.2 or with the ignore, the properties in the base type are treated as fallthrough attr
s at runtime.

anonymous.vue
4  |  import { cn } from '~/lib/utils'
5  |  
6  |  interface Props extends PrimitiveProps {
   |                          ^^^^^^^^^^^^^^
7  |    variant?: NonNullable<Parameters<typeof buttonVariants>[0]>['variant']
8  |    size?: NonNullable<Parameters<typeof buttonVariants>[0]>['size']

```

`button` folder gets added in `src/components/ui` but it doesn't get populated with the `button` component. It is specifically `button` component. When I tried to add `input`, `badge` and `alert` it worked just fine. When I tried to install `chadcn-vue` in a typescript nuxt project installing `button` works fine.

### Expected behavior

`chadcn-vue` Button component gets added to `src/components/ui` with it's `index.js` file.

**Comment by hubcio2115** [comment]
After some digging I figured that the issue might be with this utility:
```typescript
export async function transformByDetype(content: string, filename: string) {
  return await transform(content, filename, {
    removeTsComments: true,
  })
}
```
It can't convert extended interface. Maybe changing this to a `type` syntax'd solve the issue? I can't easily test it since the cli is making a fetch request to the components registry.

**Comment by hubcio2115** [comment]
I managed to get the component finally by moving `PrimitiveProps` properties to `Props`. With that I was able to build the `Button` component.

**Comment by zernonia** [comment]
Thanks for the context @hubcio2115 ! I think you are right that the transformation may be causing that issue.
@Dunqing  can you help look into this? 😁 Believe it might be related to `detypes`

**Comment by Dunqing** [comment]
> Thanks for the context @hubcio2115 ! I think you are right that the transformation may be causing that issue.
> @Dunqing can you help look into this? 😁 Believe it might be related to `detypes`

I'll look into that

**Comment by bjorne84** [comment]
I had the exact same problem/errormsg, when I installed typescript in the project it worked

**Comment by hubcio2115** [comment]
> ...when I installed typescript in the project it worked

I also have typescript installed because it's a needed dependency in a project for Volar to work. At least for me it's needed with the setup I have.

**Comment by Dunqing** [comment]
Sorry, it took so long to respond.

I cannot reproduce in your reproduction. Judging from the error message, your `@vue/compiler-sfc` package version is below v3.2. But the `detypes` package requires `@vue/*` >= `3.2`. So you can upgrade these packages and try again

<img width="1470" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/29533304/2f844e18-f5f3-4b8c-b62c-a813a64d4b3f">

**Comment by sadeghbarati** [comment]
Yes I can confirm it is working on Windows and also unix OS (StackBlitz)

https://stackblitz.com/edit/github-w623yc 
ignore this warn for now (WARN  Two component files resolving to the same name UiButton)

---

However on Windows on first try I had error but after first try it work as excepted

1. `pnpm dlx shadcn-vue@latest add button` ❌ 
2. `pnpm dlx shadcn-vue@latest add` and select the components ✅ 
3. `pnpm dlx shadcn-vue@latest add button` ✅ 


---

Please try on latest Nuxt and Vue versions, don't stay on older versions when it's not like Vue2->Vue3 migration

**Comment by Jahan-Shah** [comment]
I'm also getting this error while adding button. I just setup an vue project using js and I cannot add button to my project. Here is the link to the codespace https://codespaces.new/Jahan-Shah/test

Is there any solution?

Note: The issue resolved after I installed radix-vue.

**Comment by sadeghbarati** [comment]
Since button is using `PrimitiveProps` types 

`radix-vue` must be present in dependencies

**Comment by sadeghbarati** [comment]
Main shadcn-ui CLI also install [`@radix-ui/react-slot`](https://github.com/shadcn-ui/ui/blob/1cf5fad881b1da8f96923b7ad81d22d0aa3574b9/apps/www/registry/registry.ts#L42) when adding `Button` component

**Comment by sadeghbarati** [comment]
Ow man You guys are right 👍 

Adding `radix-vue` dep with `shadcn init` before adding any component with `shadcn-vue add` should resolve this issue

**Comment by Jahan-Shah** [comment]
@sadeghbarati I'm glad that helped in resolving the issue.

**Comment by BobbyLin23** [comment]
I am having same problems when I create a new nuxt project and install shadcn-vue button. I have already installed the `radix-vue` in deps but it's still not working.My nuxt version is 3.9 and vue version is 3.4.5.
<img width="1095" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/18840664/5a28f366-8cf6-49b0-85c4-d48af167a8e2">

**Comment by jd-solanki** [comment]
I'm still getting this error when I follow Nuxt guide: https://www.shadcn-vue.com/docs/installation/nuxt.html

I also tried installing radix-vue first and later executing `npx shadcn-vue@latest init` but still gettting the error with button component.

**Comment by Saveliy113** [comment]
> I'm still getting this error when I follow Nuxt guide: https://www.shadcn-vue.com/docs/installation/nuxt.html
> 
> I also tried installing radix-vue first and later executing `npx shadcn-vue@latest init` but still gettting the error with button component.

Same error. How to resolve it?

**Comment by ayaanqui** [comment]
I've got the same issue on a new Nuxt project. Tried adding `radix-vue` as a dev dependecy, but that didn't resolve the issue.

**Comment by sadeghbarati** [comment]
@ayaanqui Hi

Are you using `shadcn-vue` without TypeScript?

**Comment by ayaanqui** [comment]
> @ayaanqui Hi
> 
> Are you using `shadcn-vue` without TypeScript?

@sadeghbarati I'm using it with TS. Also, I was able to fix the issue on my end by adding an import to the button component. Looks like the auto import feature offered in Nuxt didn't work.

**Comment by falcon9r** [comment]
I have the same problem with typescript

please solve that

**Comment by sadeghbarati** [comment]
Hi, Can you guys share what way you using shadcn-vue in Nuxt?

- shadcn-nuxt

Or

- manual shadcn module

**Comment by serman** [comment]
Hello I have created a new project in NUXT3, I followed the instructions and I am still getting this error when using the button component. I selected the typescript option.  Is there any temporary fix?

**Comment by serman** [comment]
My fault sorry, typescript wasn't installed as a dependency:

`npm install -D typescript`

Now everything works

**Comment by sadeghbarati** [comment]
So we tested with `TypeScript` and also tested out without `TypeScript` here 👇 

https://stackblitz.com/edit/vitejs-vite-1tta2g

It's working fine

**Comment by Matheun** [comment]
still having this issue when using the default nuxt layer setup:
ENOENT: no such file or directory, stat 'D:/Code/Nuxt Component Layer - Test/nuxt-layer/.nuxt/tsconfig.json'

**Comment by usmanibrahim74** [comment]
Hi, I'm trying to use it in a Laravel project without typescript. It is not working for me also. it looks like the init command didn't installed the basic dependencies. I attached package.json after installing shadcn. should I manually install required dependencies?
![image](https://github.com/radix-vue/shadcn-vue/assets/20674784/1623570d-0b21-4690-9607-740fbf3dc6b1)
![image](https://github.com/radix-vue/shadcn-vue/assets/20674784/4844ebe0-2ba2-4227-bc7c-0aecc3ae415f)

**Comment by sadeghbarati** [comment]
@usmanibrahim74 

You need to remove lockfile and install again, then run shadcn-vue init again 

Or just install missing dependencies manually 

Idk why it's happening, but I know sometimes lockfiles are the problems

**Comment by x1q2q** [comment]
> @usmanibrahim74
> 
> You need to remove lockfile and install again, then run shadcn-vue init again
> 
> Or just install missing dependencies manually
> 
> Idk why it's happening, but I know sometimes lockfiles are the problems

thanks, dude. it works!

**Comment by sugoidesune** [comment]
Got that error too now. Fresh install of shadcn using the recommended `npx nuxi@latest module add shadcn-nuxt`
I tried updating @vue/compiler-sfc and installing updating 'radix-vue' manually but that didnt change anything.

I now added the by the compiler proposed `interface Props extends  /* @vue-ignore */ PrimitiveProps {` and it works but yeah doesn't feel like a correct solution.

    "nuxt": "^3.11.2",
    "shadcn-nuxt": "^0.10.4"
     "radix-vue": "^1.8.0",

**Comment by BlueBazze** [comment]
Been slamming my head against the wall for some days now. Same problem as the original issue, same setup as the previous comment with `Nuxt 3.11.2`
Using the managed shadcn-nuxt module, and all the default values for the configs.
The error is not specifically for the button component im my case. The same error is thrown for any import of radix component props that uses the primitive props from what ive noticed.

**Comment by mwanikigeorge** [comment]
Make sure you install typeScript as a dev dependency

**Comment by pazfelipe** [comment]
> I had the exact same problem/errormsg, when I installed typescript in the project it worked

Thank you ... adding typescript was enough to make it work.

**Comment by joeimer** [comment]
I had the same problem using nuxt + pnpm. I had to install radix-vue and tailwind-merge manually.

**Comment by alisher-abdimuminov** [comment]
just add `typescript`

`bun add -D typescript`

**Comment by ykcory** [comment]
I also discovered this issue in nuxt 4.1

**Comment by Moonlight63** [comment]
Same error on fresh nuxt 3.17.3

**Comment by EgorMalyshev99** [comment]
Is there a fix? I spent a day searching for a solution. Installing typescript didn't help.
Nuxt 4.1.2
Vue 3.5.21
shadcn-nuxt 2.2.0

**Comment by Psycarlo** [comment]
Getting this problem. I have the same versions as @EgorMalyshev99 

```json
"vue": "^3.5.21",
"nuxt": "^4.1.2",
"shadcn-nuxt": "2.2.0",
```

Installing typescript as devDependency fixed my problem:

```bash
pnpm add -D typescript
```

**Comment by joaolisboa** [comment]
Also having this issue as of today, after updating to latest versions

```
    "nuxt": "^4.2.2",
    "reka-ui": "^2.6.1",
    "shadcn-nuxt": "^2.4.3",
    "vue": "^3.5.25",
```

I've tried:
- tried downgrading versions of nuxt/shadcn-vue/reka-ui/vue
- deleting package-lock and reinstalling packages
- rerunning shadcn init and adding again all components

Still having issues:

```
 Nuxt build error: Error: [vite:vue] [@vue/compiler-sfc] Failed to resolve extends base type.
│  If this previously worked in 3.2, you can instruct the compiler to ignore this extend by adding /* @vue-ignore */ before it, for example:                                                    

│  interface Props extends /* @vue-ignore */ Base {}

│  Note: both in 3.2 or with the ignore, the properties in the base type are treated as fallthrough attrs at runtime.

│  /Users/joaolisboa/Work/mygon-admin/node_modules/reka-ui/dist/index.d.ts
│  642|  //#region src/Dialog/DialogContent.vue.d.ts
│  643|  type DialogContentEmits = DialogContentImplEmits;
│  644|  interface DialogContentProps extends Omit<DialogContentImplProps, 'trapFocus'> {
│     |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│  645|    /**
│  646|     * Used to force mounting when more control is needed. Useful when
```

**Comment by DMiradakis** [comment]
Ran into the same issue with Nuxt v4.3.0, [adding Typescript as a dev dependency](https://github.com/unovue/shadcn-vue/issues/207#issuecomment-3340909989) seemed to fix my issue (using npm).

My `package.json` below:
```json
  "dependencies": {
    "@tailwindcss/vite": "^4.1.18",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "lucide-vue-next": "^0.563.0",
    "nuxt": "^4.3.0",
    "reka-ui": "^2.8.0",
    "shadcn-nuxt": "^2.4.3",
    "tailwind-merge": "^3.4.0",
    "tailwindcss": "^4.1.18",
    "vue": "^3.5.27",
    "vue-router": "^4.6.4"
  },
  "devDependencies": {
    "tw-animate-css": "^1.4.0",
    "typescript": "^5.9.3"
  }
```

**Comment by Gkcrafting** [comment]
At first, I tried installing Typescript as a dev dependency like the previous comments said, only to realise I already had it and the error still occurred. Then I downgraded my typescript version from 7.0.2 to 5.9.3 in my package.json and now it's working perfectly.

**Comment by emullan-ads** [comment]
> Ran into the same issue with Nuxt v4.3.0, [adding Typescript as a dev dependency](https://github.com/unovue/shadcn-vue/issues/207#issuecomment-3340909989) seemed to fix my issue (using npm).
> 
> My `package.json` below:
> 
>   "dependencies": {
>     "@tailwindcss/vite": "^4.1.18",
>     "class-variance-authority": "^0.7.1",
>     "clsx": "^2.1.1",
>     "lucide-vue-next": "^0.563.0",
>     "nuxt": "^4.3.0",
>     "reka-ui": "^2.8.0",
>     "shadcn-nuxt": "^2.4.3",
>     "tailwind-merge": "^3.4.0",
>     "tailwindcss": "^4.1.18",
>     "vue": "^3.5.27",
>     "vue-router": "^4.6.4"
>   },
>   "devDependencies": {
>     "tw-animate-css": "^1.4.0",
>     "typescript": "^5.9.3"
>   }

This was the fix for me as well!
